CREATE DATABASE IF NOT EXISTS formulario;
USE formulario;

CREATE TABLE contatos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  mensagem VARCHAR(250) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);